### ISSUE TITLE
make `print()` more useful, avoid corrupting stdout TUI

### ISSUE THREAD

**Issue by jhall11** [mudpuppy-rs/mudpuppy#16]
I noticed a few issues when evaluating the following command:
`/py print(\"strings needs to be escaped\")`

I'm not sure if the output was intended to be in the input prompt or in the regular history buffer, but it is currently displayed in the input prompt and
1. the output starts at the position to the right of where the command ended, ie if the command was n characters the output starts at n+1
2. the output is not cleared until the user types over the characters, even if sending new commands

**Comment by cpu** [comment]
Thanks for filing an issue about this. In general I'm not very happy with the state of the `/py` command right now. It's not a great "REPL" environment since everything it executes has to be a stand-alone expression. E.g. you can't `import logging` and then use it, it'd have to be [injected as a global](https://github.com/mudpuppy-rs/mudpuppy/blob/9792e067f35e13df0788dd63092e8286eb840899/mudpuppy/python/cmd_py.py#L31-L39).

> I'm not sure if the output was intended to be in the input prompt or in the regular history buffer, but it is currently displayed in the input prompt

Yeah, anything that writes to `stdout` like `print()` is going to splat its contents all over the TUI, which results in the weird glitches you mention in 2.

My general intent is that to display output in the main buffer without corrupting the TUI you should add output like:

```python
  await mudpuppy_core.add_output(
        session_id, OutputItem.command_result("strings need to be escaped")
    )
```

The alternative is to use Python's `logging` package which I've hijacked to push into the same log as the Rust code (but as mentioned, I think doing either is tricky with the `/py` command in its current state). You could also write to `stderr`, but the results won't be visible until you quit the application.

One action item to take here is to see if we can override the `print` function to do something smarter since we know printing directly to `stdout` is always going to be the wrong thing.

**Comment by jhall11** [comment]
I totally agree that it would be nice to have it be more of a "REPL" env, being able to save variables and access then later would be nice, even if you only had access to the "console" namespace and nothing created by scripts. 

I think ideally there would be "console" friendly versions of some functions which could just be wrappers to make them less verbose to type. It would be nice to do something like `/py send("hello world")` with the session id as an optional argument and the current session being the default. I haven't looked too closely, or even created a second session yet, but it seems like it might be a little awkward trying to keep them straight from the command line.

**Comment by cpu** [comment]
> I totally agree that it would be nice to have it be more of a "REPL" env, being able to save variables and access then later would be nice, even if you only had access to the "console" namespace and nothing created by scripts.

I think I have an idea for how to make that workable :test_tube: :microscope: I'll carve out a separate issue later today.

> It would be nice to do something like /py send("hello world") with the session id as an optional argument and the current session being the default.

100% - I think a lot of the APIs that exist so far are pretty "low-level" and should eventually be wrapped up with better ergonomics, kind of like the `mudpuppy` decorators around `mudpuppy_core` bits. I'll start a list for this too.
